version: '3'
services:
  web:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app

    ports:
      - '3000:3000'
    command: npm start

  database:
    image: mongo:latest
    volumes:
      - mongodata:/data/db
    ports:
      - '3001:3001'
volumes:
  mongodata:



  #  client:
  #    build: ./client
  #    container_name: client_frontend
  #    ports:
  #      - '3000:3000'
  #    volumes:
  #      - ./client:/app
  #      - ./app/node_modules
#  stdin_open: true
#  tty: true